// examples/angular/src/app/app.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { ThemeService } from './theme.service';

@Component({
  selector: 'app-root',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <main>
      <h1>Nokturne + Angular</h1>
      <p>choice: <strong>{{ theme.state().theme }}</strong></p>
      <p>resolved: <strong>{{ theme.state().resolvedTheme }}</strong></p>
      <p>system: <strong>{{ theme.state().systemTheme }}</strong></p>
      <div class="row">
        <button (click)="theme.setTheme('light')">Light</button>
        <button (click)="theme.setTheme('dark')">Dark</button>
        <button (click)="theme.setTheme('system')">System</button>
        <button (click)="theme.toggle()">Toggle</button>
      </div>
    </main>
  `,
})
export class App {
  protected readonly theme = inject(ThemeService);
}

// examples/react/src/App.tsx
import { useTheme } from 'nokturne/react';

export default function App() {
  const { theme, resolvedTheme, systemTheme, setTheme, toggle } = useTheme();

  return (
    <main>
      <h1>Nokturne + React</h1>
      <p>choice: <strong>{theme}</strong></p>
      <p>resolved: <strong>{resolvedTheme}</strong></p>
      <p>system: <strong>{systemTheme}</strong></p>
      <div className="row">
        <button onClick={() => setTheme('light')}>Light</button>
        <button onClick={() => setTheme('dark')}>Dark</button>
        <button onClick={() => setTheme('system')}>System</button>
        <button onClick={toggle}>Toggle</button>
      </div>
    </main>
  );
}
