// examples/vue/src/App.vue
<script setup lang="ts">
import { useTheme } from 'nokturne/vue';

const { theme, resolvedTheme, systemTheme, setTheme, toggle } = useTheme();
</script>

<template>
  <main>
    <h1>Nokturne + Vue</h1>
    <p>choice: <strong>{{ theme }}</strong></p>
    <p>resolved: <strong>{{ resolvedTheme }}</strong></p>
    <p>system: <strong>{{ systemTheme }}</strong></p>
    <div class="row">
      <button @click="setTheme('light')">Light</button>
      <button @click="setTheme('dark')">Dark</button>
      <button @click="setTheme('system')">System</button>
      <button @click="toggle">Toggle</button>
    </div>
  </main>
</template>

// examples/react/src/App.tsx
import { useTheme } from 'nokturne/react';

export default function App() {
  const { theme, resolvedTheme, systemTheme, setTheme, toggle } = useTheme();

  return (
    <main>
      <h1>Nokturne + React</h1>
      <p>choice: <strong>{theme}</strong></p>
      <p>resolved: <strong>{resolvedTheme}</strong></p>
      <p>system: <strong>{systemTheme}</strong></p>
      <div className="row">
        <button onClick={() => setTheme('light')}>Light</button>
        <button onClick={() => setTheme('dark')}>Dark</button>
        <button onClick={() => setTheme('system')}>System</button>
        <button onClick={toggle}>Toggle</button>
      </div>
    </main>
  );
}
