// examples/vue/src/App.vue
<script setup lang="ts">
import { useTheme } from 'nokturne/vue';

const { theme, resolvedTheme, systemTheme, setTheme, toggle } = useTheme();
</script>

<template>
  <main>
    <h1>Nokturne + Vue</h1>
    <p>choice: <strong>{{ theme }}</strong></p>
    <p>resolved: <strong>{{ resolvedTheme }}</strong></p>
    <p>system: <strong>{{ systemTheme }}</strong></p>
    <div class="row">
      <button @click="setTheme('light')">Light</button>
      <button @click="setTheme('dark')">Dark</button>
      <button @click="setTheme('system')">System</button>
      <button @click="toggle">Toggle</button>
    </div>
  </main>
</template>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { themeStore } from 'nokturne/svelte';

  const theme = themeStore();
</script>

<main>
  <h1>Nokturne + Svelte</h1>
  <p>choice: <strong>{$theme.theme}</strong></p>
  <p>resolved: <strong>{$theme.resolvedTheme}</strong></p>
  <p>system: <strong>{$theme.systemTheme}</strong></p>
  <div class="row">
    <button onclick={() => theme.setTheme('light')}>Light</button>
    <button onclick={() => theme.setTheme('dark')}>Dark</button>
    <button onclick={() => theme.setTheme('system')}>System</button>
    <button onclick={theme.toggle}>Toggle</button>
  </div>
</main>
